export const currencies = [
  { label: "United States Dollar", value: "USD", symbol: "$" },
  { label: "Euro", value: "EUR", symbol: "€" },
  { label: "British Pound", value: "GBP", symbol: "£" },
  { label: "Japanese Yen", value: "JPY", symbol: "¥" },
  { label: "Canadian Dollar", value: "CAD", symbol: "C$" },
  { label: "Australian Dollar", value: "AUD", symbol: "A$" },
  { label: "Swiss Franc", value: "CHF", symbol: "CHF" },
  { label: "Chinese Yuan", value: "CNY", symbol: "¥" },
  { label: "Indian Rupee", value: "INR", symbol: "₹" },
  { label: "Brazilian Real", value: "BRL", symbol: "R$" },
  { label: "Russian Ruble", value: "RUB", symbol: "₽" },
  { label: "South African Rand", value: "ZAR", symbol: "R" },
  { label: "New Zealand Dollar", value: "NZD", symbol: "NZ$" },
  { label: "Mexican Peso", value: "MXN", symbol: "Mex$" },
  { label: "Singapore Dollar", value: "SGD", symbol: "S$" },
  { label: "Hong Kong Dollar", value: "HKD", symbol: "HK$" },
  { label: "Norwegian Krone", value: "NOK", symbol: "kr" },
  { label: "Swedish Krona", value: "SEK", symbol: "kr" },
  { label: "South Korean Won", value: "KRW", symbol: "₩" },
  { label: "Turkish Lira", value: "TRY", symbol: "₺" },
  { label: "Indonesian Rupiah", value: "IDR", symbol: "Rp" },
  { label: "Malaysian Ringgit", value: "MYR", symbol: "RM" },
  { label: "Philippine Peso", value: "PHP", symbol: "₱" },
  { label: "Thai Baht", value: "THB", symbol: "฿" },
  { label: "Polish Zloty", value: "PLN", symbol: "zł" },
  { label: "Danish Krone", value: "DKK", symbol: "kr" },
  { label: "Hungarian Forint", value: "HUF", symbol: "Ft" },
  { label: "Czech Koruna", value: "CZK", symbol: "Kč" },
  { label: "Israeli New Shekel", value: "ILS", symbol: "₪" },
  { label: "Chilean Peso", value: "CLP", symbol: "CLP$" },
  { label: "Colombian Peso", value: "COP", symbol: "COL$" },
  { label: "Saudi Riyal", value: "SAR", symbol: "﷼" },
  { label: "UAE Dirham", value: "AED", symbol: "د.إ" },
  { label: "Egyptian Pound", value: "EGP", symbol: "E£" },
  { label: "Pakistani Rupee", value: "PKR", symbol: "₨" },
  { label: "Bangladeshi Taka", value: "BDT", symbol: "৳" },
  { label: "Nigerian Naira", value: "NGN", symbol: "₦" },
  { label: "Vietnamese Dong", value: "VND", symbol: "₫" },
  { label: "Ukrainian Hryvnia", value: "UAH", symbol: "₴" },
  { label: "Argentine Peso", value: "ARS", symbol: "$" },
  { label: "Algerian Dinar", value: "DZD", symbol: "د.ج" },
  { label: "Kenyan Shilling", value: "KES", symbol: "KSh" },
  { label: "Iraqi Dinar", value: "IQD", symbol: "ع.د" },
  { label: "Kazakhstani Tenge", value: "KZT", symbol: "₸" },
  { label: "Uzbekistan Sum", value: "UZS", symbol: "сум" },
  { label: "Ghanaian Cedi", value: "GHS", symbol: "₵" },
  { label: "CFA Franc BEAC", value: "XAF", symbol: "FCFA" },
  { label: "CFA Franc BCEAO", value: "XOF", symbol: "CFA" },
  { label: "Ugandan Shilling", value: "UGX", symbol: "USh" },
  { label: "Tanzanian Shilling", value: "TZS", symbol: "TSh" },
  { label: "Sri Lankan Rupee", value: "LKR", symbol: "Rs" },
  { label: "Nepalese Rupee", value: "NPR", symbol: "रू" },
  { label: "Afghan Afghani", value: "AFN", symbol: "؋" },
  { label: "Albanian Lek", value: "ALL", symbol: "L" },
  { label: "Armenian Dram", value: "AMD", symbol: "֏" },
  { label: "Angolan Kwanza", value: "AOA", symbol: "Kz" },
  { label: "Azerbaijani Manat", value: "AZN", symbol: "₼" },
  { label: "Bosnia-Herzegovina Convertible Mark", value: "BAM", symbol: "KM" },
  { label: "Barbadian Dollar", value: "BBD", symbol: "Bds$" },
  { label: "Bulgarian Lev", value: "BGN", symbol: "лв" },
  { label: "Bahraini Dinar", value: "BHD", symbol: ".د.ب" },
  { label: "Burundian Franc", value: "BIF", symbol: "FBu" },
  { label: "Bermudan Dollar", value: "BMD", symbol: "BD$" },
  { label: "Brunei Dollar", value: "BND", symbol: "B$" },
  { label: "Bolivian Boliviano", value: "BOB", symbol: "Bs." },
  { label: "Bahamian Dollar", value: "BSD", symbol: "B$" },
  { label: "Bhutanese Ngultrum", value: "BTN", symbol: "Nu." },
  { label: "Botswanan Pula", value: "BWP", symbol: "P" },
  { label: "Belarusian Ruble", value: "BYN", symbol: "Br" },
  { label: "Belize Dollar", value: "BZD", symbol: "BZ$" },
  { label: "Congolese Franc", value: "CDF", symbol: "FC" },
  { label: "Costa Rican Colón", value: "CRC", symbol: "₡" },
  { label: "Cuban Peso", value: "CUP", symbol: "₱" },
  { label: "Cape Verdean Escudo", value: "CVE", symbol: "Esc" },
  { label: "Djiboutian Franc", value: "DJF", symbol: "Fdj" },
  { label: "Dominican Peso", value: "DOP", symbol: "RD$" },
  { label: "Eritrean Nakfa", value: "ERN", symbol: "Nfk" },
  { label: "Ethiopian Birr", value: "ETB", symbol: "Br" },
  { label: "Fijian Dollar", value: "FJD", symbol: "FJ$" },
  { label: "Falkland Islands Pound", value: "FKP", symbol: "£" },
  { label: "Georgian Lari", value: "GEL", symbol: "₾" },
  { label: "Guernsey Pound", value: "GGP", symbol: "£" },
  { label: "Gibraltar Pound", value: "GIP", symbol: "£" },
  { label: "Gambian Dalasi", value: "GMD", symbol: "D" },
  { label: "Guinean Franc", value: "GNF", symbol: "FG" },
  { label: "Guatemalan Quetzal", value: "GTQ", symbol: "Q" },
  { label: "Guyanaese Dollar", value: "GYD", symbol: "GY$" },
  { label: "Honduran Lempira", value: "HNL", symbol: "L" },
  { label: "Croatian Kuna", value: "HRK", symbol: "kn" },
  { label: "Haitian Gourde", value: "HTG", symbol: "G" },
  { label: "Isle of Man Pound", value: "IMP", symbol: "£" },
  { label: "Iranian Rial", value: "IRR", symbol: "﷼" },
  { label: "Icelandic Króna", value: "ISK", symbol: "kr" },
  { label: "Jersey Pound", value: "JEP", symbol: "£" },
  { label: "Jamaican Dollar", value: "JMD", symbol: "J$" },
  { label: "Jordanian Dinar", value: "JOD", symbol: "JD" },
  { label: "Kyrgyzstani Som", value: "KGS", symbol: "с" },
  { label: "Cambodian Riel", value: "KHR", symbol: "៛" },
  { label: "Comorian Franc", value: "KMF", symbol: "CF" },
  { label: "North Korean Won", value: "KPW", symbol: "₩" },
  { label: "Kuwaiti Dinar", value: "KWD", symbol: "KD" },
  { label: "Cayman Islands Dollar", value: "KYD", symbol: "CI$" },
  { label: "Laotian Kip", value: "LAK", symbol: "₭" },
  { label: "Lebanese Pound", value: "LBP", symbol: "ل.ل" },
  { label: "Liberian Dollar", value: "LRD", symbol: "L$" },
  { label: "Lesotho Loti", value: "LSL", symbol: "L" },
  { label: "Libyan Dinar", value: "LYD", symbol: "ل.د" },
  { label: "Moroccan Dirham", value: "MAD", symbol: "د.م." },
  { label: "Moldovan Leu", value: "MDL", symbol: "L" },
  { label: "Malagasy Ariary", value: "MGA", symbol: "Ar" },
  { label: "Macedonian Denar", value: "MKD", symbol: "ден" },
  { label: "Myanma Kyat", value: "MMK", symbol: "Ks" },
  { label: "Mongolian Tugrik", value: "MNT", symbol: "₮" },
  { label: "Macanese Pataca", value: "MOP", symbol: "MOP$" },
  { label: "Mauritanian Ouguiya", value: "MRU", symbol: "UM" },
  { label: "Mauritian Rupee", value: "MUR", symbol: "₨" },
  { label: "Maldivian Rufiyaa", value: "MVR", symbol: "Rf" },
  { label: "Malawian Kwacha", value: "MWK", symbol: "MK" },
  { label: "Mozambican Metical", value: "MZN", symbol: "MT" },
  { label: "Namibian Dollar", value: "NAD", symbol: "N$" },
  { label: "Nicaraguan Córdoba", value: "NIO", symbol: "C$" },
  { label: "Omani Rial", value: "OMR", symbol: "ر.ع." },
  { label: "Panamanian Balboa", value: "PAB", symbol: "B/." },
  { label: "Peruvian Sol", value: "PEN", symbol: "S/." },
  { label: "Papua New Guinean Kina", value: "PGK", symbol: "K" },
  { label: "Paraguayan Guarani", value: "PYG", symbol: "₲" },
  { label: "QAR - Qatari Rial", value: "QAR", symbol: "ر.ق" },
  { label: "Romanian Leu", value: "RON", symbol: "lei" },
  { label: "Serbian Dinar", value: "RSD", symbol: "дин." },
  { label: "Rwandan Franc", value: "RWF", symbol: "RF" },
  { label: "Solomon Islands Dollar", value: "SBD", symbol: "SI$" },
  { label: "Seychellois Rupee", value: "SCR", symbol: "SR" },
  { label: "Sudanese Pound", value: "SDG", symbol: "ج.س." },
  { label: "South Sudanese Pound", value: "SSP", symbol: "£" },
  { label: "São Tomé and Príncipe Dobra", value: "STN", symbol: "Db" },
  { label: "Salvadoran Colón", value: "SVC", symbol: "₡" },
  { label: "Syrian Pound", value: "SYP", symbol: "£S" },
  { label: "Swazi Lilangeni", value: "SZL", symbol: "E" },
  { label: "Tajikistani Somoni", value: "TJS", symbol: "ЅМ" },
  { label: "Turkmenistani Manat", value: "TMT", symbol: "m" },
  { label: "Tunisian Dinar", value: "TND", symbol: "د.ت" },
  { label: "Tongan Paʻanga", value: "TOP", symbol: "T$" },
  { label: "Trinidad and Tobago Dollar", value: "TTD", symbol: "TT$" },
  { label: "New Taiwan Dollar", value: "TWD", symbol: "NT$" },
  { label: "Uruguayan Peso", value: "UYU", symbol: "$" },
  { label: "Venezuelan Bolívar Soberano", value: "VES", symbol: "Bs.S" },
  { label: "Vanuatu Vatu", value: "VUV", symbol: "Vt" },
  { label: "Samoan Tala", value: "WST", symbol: "WS$" },
  { label: "East Caribbean Dollar", value: "XCD", symbol: "EC$" },
  { label: "CFP Franc", value: "XPF", symbol: "CFP" },
  { label: "Yemeni Rial", value: "YER", symbol: "﷼" },
  { label: "Zambian Kwacha", value: "ZMW", symbol: "ZK" },
  { label: "Zimbabwean Dollar", value: "ZWL", symbol: "Z$" },
].sort((a, b) => a.label.localeCompare(b.label));